<?xml version="1.0" encoding="utf-8"?><Database Name="Coordination" Class="CoordinationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Coordination;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CoordinationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.cooperation" Member="cooperation">
    <Type Name="cooperation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mark" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="data" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="announcer" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="releasetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="users">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="student_id" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="student_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="mark" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="states" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.demand" Member="demand">
    <Type Name="demand">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mark" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="data" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.team" Member="team">
    <Type Name="team">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mark" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="heading" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="schedule" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.testform" Member="testform">
    <Type Name="testform">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mark" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="field" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="complete" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>